import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRecoilState, useRecoilValue } from 'recoil'
import { userState, nameState } from '../store/user'
import { useRouter } from 'next/dist/client/router'

const First: NextPage = () => {
  const route = useRouter()
  const charUser = useRecoilValue(nameState)
  const [user, setUser] = useRecoilState(userState)

  const handleActive = () => {
    setUser(per => ({
      ...per,
      active: !per.active
    }))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Recoil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Recoil First</a>
        </h1>

        <div className={styles.grid}>
          ชื่อ {user?.name} อายุ {user?.age} ปี สถานะ {user.active ? 'เปิดการใช้งาน' : 'ปิดการใช้งาน'}
        </div>

        <button onClick={handleActive}>คลิก</button>

        <div className={styles.grid}>
          {charUser} จำนวนชื่อ
        </div>

        <button onClick={() => route.push('first')}>คลิก</button>


      </main>

    </div>
  )
}

export default First
