import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRecoilState, useRecoilValue, useSetRecoilState } from 'recoil'
import { userState, nameState } from '../store/user'
import { useRouter } from 'next/dist/client/router'

const Home: NextPage = () => {
  const route = useRouter()
  const setName = useSetRecoilState(userState)
  const name = useRecoilValue(nameState)
  const [user, setUser] = useRecoilState(userState)

  const handleActive = () => {
    console.log(name)
    setName({
      name: 'xxxx',
      age: 10,
      active: false
    })
    // setUser(per => ({
    //   ...per,
    //   active: !per.active
    // }))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Recoil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Recoil Home</a>
        </h1>

        <div className={styles.grid}>
          ชื่อ {user?.name} อายุ {user?.age} ปี สถานะ {user.active ? 'เปิดการใช้งาน' : 'ปิดการใช้งาน'} <button onClick={handleActive}>คลิก</button>
        </div>

        <div className={styles.grid}>
          ความยาวชื่อ {name} ตัวอักษร
        </div>

        {/* <button onClick={() => route.push('/first')}>first page</button> */}

      </main>

    </div>
  )
}

export default Home
